name: Repo Sync

on:
  schedule:
  - cron: "*/15 * * * *"

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        source_repo: https://github.com/IFCA-Advanced-Computing/FAIR_eva
        source_branch: main
        destination_branch: repo-sync
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # - uses: repo-sync/pull-request@v2
    #   name: Create pull request
    #   with:
    #     source_branch: repo-sync
    #     destination_branch: merge/repo-sync
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
